### PR TITLE
Implement BFT

### PR DESCRIPTION
**Pull request by nmraz**
Things left to implement:

- [ ] Use of `cluster_offset_t`
EDIT: Will be implemented as soon as cluster is done.

- [x] `bft_write_table` and `bft_read_table`

### CODE REVIEW

**Comment by ThatFatPat** [comment]
Aren't we missing a few functions? Where is rw table?

**Comment by nmraz** [comment]
If you're talking about `bft_read_table` and `bf_write_table`, they depend on stego as I mentioned above.

**Comment by ThatFatPat** [comment]
Yes. Sorry, I missed that.
I think I would wait with this merge until they can be fully implemented.

**Comment by nmraz** [comment]
Okay. I'm leaving this open for tracking and discussion.

**Pull request merged**
